config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => {
  :sessions => 'admins/sessions'
  }

  devise_for :users, :controllers => {
  :sessions => 'users/sessions',
  :registrations => 'users/registrations',
  }
  
  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'public/users#top'
  get 'about' =>'public/users#about'

  namespace :admin do
    resources :areas
    resources :purposes
    resources :spots
  end

  scope module: :public do
    resources :users
    resources :areas
    resources :purposes
    resources :spots, only:[:index, :show] do
      resources :spot_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get '/spots/:area_id/eria/:purpose_id', to: 'spots#eria_mokuteki', as: 'eria_purpose'
    get '/spots/mokuteki/:purpose_id', to: 'spots#mokuteki', as: 'mokuteki'
    
    get "search" => "searches#search"
  end
  
  
end

app/controllers/admin/purposes_controller.rb
class Admin::PurposesController < ApplicationController
  
  before_action :authenticate_admin!
  def index
    @purpose = Purpose.new
    @purposes = Purpose.all
  end

  def create
    @purpose = Purpose.new(purpose_params)
    @purpose.save
    redirect_to admin_purposes_path
  end

  def destroy
    @purposes = Purpose.find(params[:id])
    @purposes.destroy
    redirect_to admin_purposes_path
  end

  private

  def purpose_params
    params.require(:purpose).permit(:name, :image)
  end

end

app/helpers/admin/purposes_helper.rb
module Admin::PurposesHelper
end

app/views/admin/purposes/index.html.erb
<div class="admin">
  <h1>目的一覧</h1>
  <%= form_with model: @purpose,url: admin_purposes_path(@purpose), local:true do |f| %>
  <div>
    <%= f.label :image_id, "目的画像" %>
    <%= f.attachment_field :image %>
  </div>
  <div>
    <%= f.label :name, "目的名" %>
    <%= f.text_field :name %>
  </div>
    <%= f.submit "追加" %>
  <% end %>
    <table class="admin">
      <thead>
        <tr>
          <th>目的画像</th>
          <th>目的名</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @purposes.each do |purpose| %>
        <tr>
          <th><%= attachment_image_tag purpose, :image, :fill, 50, 50, fallback: "no_image.jpg" %></th>
          <th><%= purpose.name %></th>
          <th><%= link_to "削除",admin_purpose_path(purpose.id), method: :delete %></th>
        </tr>
      <% end %>
      </tbody>
    </table>
</div>