config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => {
  :sessions => 'admins/sessions'
  }

  devise_for :users, :controllers => {
  :sessions => 'users/sessions',
  :registrations => 'users/registrations',
  }
  
  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'public/users#top'
  get 'about' =>'public/users#about'

  namespace :admin do
    resources :areas
    resources :purposes
    resources :spots
  end

  scope module: :public do
    resources :users
    resources :areas
    resources :purposes
    resources :spots, only:[:index, :show] do
      resources :spot_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get '/spots/:area_id/eria/:purpose_id', to: 'spots#eria_mokuteki', as: 'eria_purpose'
    get '/spots/mokuteki/:purpose_id', to: 'spots#mokuteki', as: 'mokuteki'
    
    get "search" => "searches#search"
  end
  
  
end

app/models/area.rb
class Area < ApplicationRecord

  has_many :spots, dependent: :destroy
  attachment :image
  
end

app/controllers/admin/areas_controller.rb
class Admin::AreasController < ApplicationController

  before_action :authenticate_admin!

  def index
    @areas = Area.all
  end

  def new
    @area = Area.new
  end

  def create
    @area = Area.new(area_params)
    @area.save
    redirect_to admin_areas_path
  end

  def edit
    @area = Area.find(params[:id])
  end

  def update
    @area = Area.find(params[:id])
    @area.update(area_params)
    redirect_to admin_areas_path
  end

  def destroy
    @areas = Area.find(params[:id])
    @areas.destroy
    redirect_to admin_areas_path
  end

  private

  def area_params
    params.require(:area).permit(:name, :description, :image)
  end

end

app/helpers/admin/areas_helper.rb
module Admin::AreasHelper
end

app/views/admin/areas/edit.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <h1>エリア編集</h1>
    <%= form_with model: @area, url: admin_area_path, local:true do |f| %>
      <div class="field form-group col-xs-12">
        <%= f.label :image_id, "エリア画像" %>
        <%= f.attachment_field :image %>
      </div>
      <div class="field form-group col-xs-12">
        <%= f.label :name, "エリア名" %>
        <%= f.text_field :name %>
      </div>
      <div class="field form-group col-xs-12">
        <%= f.label :description, "エリア説明" %>
        <%= f.text_area :description ,size: "4x8", class: "form-control" %>
      </div>
      <div class="field form-group col-xs-12">
        <%= f.submit "編集" %>
      </div>
    <% end %>
    <div class="field form-group col-xs-12">
      <%= link_to '戻る',admin_areas_path %>
    </div>
  </div>
</div>

app/views/admin/areas/index.html.erb
<h1 id="center">エリア一覧</h1>
<h2 id="center">
  <%= link_to "追加",new_admin_area_path %>
</h2>
<div class="album" id="center">
  <div class="container">
    <div class="row">
      <% @areas.each do |area| %>
      <div class="col-md-4">
        <div class="card md-4">
          <div class="card-imag-top text-center">
            <%= attachment_image_tag area, :image, fallback: "no_image.jpg", size: '300x200' %>
          </div>
          <div class="card-body">
            <p class="card-text-center" id="font">
              <%= area.name %>
              <%= link_to "編集",edit_admin_area_path(area.id) %>
              <%= link_to "削除",admin_area_path(area.id), method: :delete %>
            </p>
            <p><%= area.description %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/areas/new.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <h1>エリア追加</h1>
    <%= form_with model: @area, url: admin_areas_path(@area), local:true do |f| %>
    <div class="field form-group col-xs-12">
      <%= f.label :image_id, "エリア画像" %>
      <%= f.attachment_field :image %>
    </div>
    <div class="field form-group col-xs-12">
      <%= f.label :name, "エリア名" %>
      <%= f.text_field :name %>
    </div>
    <div class="field form-group col-xs-12">
     <%= f.label :description, "エリア説明" %>
      <%= f.text_area :description ,size: "4x8", class: "form-control" %>
    </div>
    <div class="field form-group col-xs-12">
      <%= f.submit "登録" %>
    </div>
    <% end %>
    <div class="field form-group col-xs-12">
      <%= link_to '戻る',admin_areas_path %>
    </div>
  </div>
</div>