config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => {
  :sessions => 'admins/sessions'
  }

  devise_for :users, :controllers => {
  :sessions => 'users/sessions',
  :registrations => 'users/registrations',
  }
  
  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'public/users#top'
  get 'about' =>'public/users#about'

  namespace :admin do
    resources :areas
    resources :purposes
    resources :spots
  end

  scope module: :public do
    resources :users
    resources :areas
    resources :purposes
    resources :spots, only:[:index, :show] do
      resources :spot_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get '/spots/:area_id/eria/:purpose_id', to: 'spots#eria_mokuteki', as: 'eria_purpose'
    get '/spots/mokuteki/:purpose_id', to: 'spots#mokuteki', as: 'mokuteki'
    
    get "search" => "searches#search"
  end
  
  
end

app/models/spot.rb
class Spot < ApplicationRecord

  has_many :spot_comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  has_many :favorited_users, through: :favorites, source: :user

  belongs_to :area
  belongs_to :purpose
  belongs_to :user,optional: true

  attachment :image

  #検索機能
  def self.search(keyword)
    @search_spots = Spot.where("name like? OR description like?", "%#{keyword}%", "%#{keyword}%")
  end

end

app/controllers/admin/spots_controller.rb
class Admin::SpotsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @spots = Spot.all.page(params[:page]).per(6)
    @areas = Area.all
    @purposes = Purpose.all
  end

  def new
    @spot = Spot.new
    @areas = Area.all
    @purposes = Purpose.all
  end

  def create
    @areas = Area.all
    @purposes = Purpose.all
    @spot = Spot.new(spot_params)
    @spot.save
    redirect_to admin_spots_path
  end

  def edit
    @areas = Area.all
    @purposes = Purpose.all
    @spot = Spot.find(params[:id])
  end

  def update
    @areas = Area.all
    @purposes = Purpose.all
    @spot = Spot.find(params[:id])
    @spot.update(spot_params)
    redirect_to admin_spots_path
  end

  def destroy
    @spots = Spot.find(params[:id])
    @spots.destroy
    redirect_to admin_spots_path
  end

  private

  def spot_params
    params.require(:spot).permit(:area_id, :purpose_id, :name, :description, :image)
  end

end

app/helpers/admin/spots_helper.rb
module Admin::SpotsHelper
end

app/views/admin/spots/edit.html.erb
<div class="row">
  <div class="col-md-12 text-center">
      <h1>スポット編集</h1>
      <%= form_with model: @spot, url: admin_spot_path(@spot.id), local:true do |f| %>
      <div class="field form-group col-xs-12">
        <%= f.label :area_id, "エリア" %>
        <%= f.collection_select :area_id, @areas, :id, :name, prompt: "選択して下さい" %>
      </div>
      <div class="field form-group col-xs-12">
        <%= f.label :purpose_id, "目的" %>
        <%= f.collection_select :purpose_id, @purposes, :id, :name, prompt: "選択して下さい" %>
      </div>
      <div class="field form-group col-xs-12">
        <%= f.label :image_id, "スポット画像" %>
        <%= f.attachment_field :image %>
      </div>
      <div class="field form-group col-xs-12">
        <%= f.label :name, "スポット名" %>
        <%= f.text_field :name %>
      </div>
      <div class="field form-group col-xs-12">
        <%= f.label :description, "スポット説明" %>
        <%= f.text_area :description ,size: "4x8", class: "form-control" %>
      </div>
      <div class="field form-group col-xs-12">
        <%= f.submit "変更" %>
      </div>
      <% end %>
      <div class="field form-group col-xs-12">
        <%= link_to '戻る',admin_spots_path %>
      </div>
  </div>
</div>

app/views/admin/spots/index.html.erb
<h1 id="center">スポット一覧</h1>
<h2 id="center"><%= link_to "追加",new_admin_spot_path %></h2>
<div class="album" id="center">
  <div class="container">
    <div class="row">
      <% @spots.each do |spot| %>
      <div class="col-md-4">
        <div class="card md-4">
          <div class="card-imag-top text-center">
            <%= attachment_image_tag spot, :image, fallback: "no_image.jpg", size: '300x200' %>
          </div>
          <div class="card-body">
            <p class="card-text-center" id="font">
              <%= spot.name %>
              <%= link_to "編集",edit_admin_spot_path(spot.id) %>
              <%= link_to "削除",admin_spot_path(spot.id), method: :delete %>
            </p>
            <p><%= spot.description %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
<%= paginate @spots %>

app/views/admin/spots/new.html.erb
<div class="row">
  <div class="col-md-12 text-center">
      <h1>スポット追加</h1>
      <%= form_with model: @spot, url: admin_spots_path(@spot), local:true do |f| %>
      <div class="field form-group col-xs-12">
        <%= f.label :area_id, "エリア" %>
        <%= f.collection_select :area_id, @areas, :id, :name, prompt: "選択して下さい" %>
      </div>
      <div class="field form-group col-xs-12">
        <%= f.label :purpose_id, "目的" %>
        <%= f.collection_select :purpose_id, @purposes, :id, :name, prompt: "選択して下さい" %>
      </div>
      <div class="field form-group col-xs-12">
        <%= f.label :image_id, "スポット画像" %>
        <%= f.attachment_field :image %>
      </div>
      <div class="field form-group col-xs-12">
        <%= f.label :name, "スポット名" %>
        <%= f.text_field :name %>
      </div>
      <div class="field form-group col-xs-12">
        <%= f.label :description, "スポット説明" %>
        <%= f.text_area :description ,size: "4x8", class: "form-control" %>
      </div>
      <div class="field form-group col-xs-12">
        <%= f.submit "登録" %>
      </div>
      <% end %>
      <div class="field form-group col-xs-12">
        <%= link_to '戻る',admin_spots_path %>
      </div>
  </div>
</div>