config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => {
  :sessions => 'admins/sessions'
  }

  devise_for :users, :controllers => {
  :sessions => 'users/sessions',
  :registrations => 'users/registrations',
  }
  
  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'public/users#top'
  get 'about' =>'public/users#about'

  namespace :admin do
    resources :areas
    resources :purposes
    resources :spots
  end

  scope module: :public do
    resources :users
    resources :areas
    resources :purposes
    resources :spots, only:[:index, :show] do
      resources :spot_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get '/spots/:area_id/eria/:purpose_id', to: 'spots#eria_mokuteki', as: 'eria_purpose'
    get '/spots/mokuteki/:purpose_id', to: 'spots#mokuteki', as: 'mokuteki'
    
    get "search" => "searches#search"
  end
  
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord

  has_many :spots, dependent: :destroy
  attachment :image
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :spot
end

app/models/purpose.rb
class Purpose < ApplicationRecord

  has_many :spots, dependent: :destroy
  attachment :image
end

app/models/spot.rb
class Spot < ApplicationRecord

  has_many :spot_comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  has_many :favorited_users, through: :favorites, source: :user

  belongs_to :area
  belongs_to :purpose
  belongs_to :user,optional: true

  attachment :image

  #検索機能
  def self.search(keyword)
    @search_spots = Spot.where("name like? OR description like?", "%#{keyword}%", "%#{keyword}%")
  end

end

app/models/spot_comment.rb
class SpotComment < ApplicationRecord

  belongs_to :user
  belongs_to :spot
  
  validates :comment, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :spots, dependent: :destroy
  has_many :spot_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_spots, through: :favorites, source: :spot
  
  
  validates :name, presence: true
  validates :age, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/admin/areas_controller.rb
class Admin::AreasController < ApplicationController

  before_action :authenticate_admin!

  def index
    @areas = Area.all
  end

  def new
    @area = Area.new
  end

  def create
    @area = Area.new(area_params)
    @area.save
    redirect_to admin_areas_path
  end

  def edit
    @area = Area.find(params[:id])
  end

  def update
    @area = Area.find(params[:id])
    @area.update(area_params)
    redirect_to admin_areas_path
  end

  def destroy
    @areas = Area.find(params[:id])
    @areas.destroy
    redirect_to admin_areas_path
  end

  private

  def area_params
    params.require(:area).permit(:name, :description, :image)
  end

end

app/controllers/admin/purposes_controller.rb
class Admin::PurposesController < ApplicationController
  
  before_action :authenticate_admin!
  def index
    @purpose = Purpose.new
    @purposes = Purpose.all
  end

  def create
    @purpose = Purpose.new(purpose_params)
    @purpose.save
    redirect_to admin_purposes_path
  end

  def destroy
    @purposes = Purpose.find(params[:id])
    @purposes.destroy
    redirect_to admin_purposes_path
  end

  private

  def purpose_params
    params.require(:purpose).permit(:name, :image)
  end

end

app/controllers/admin/spots_controller.rb
class Admin::SpotsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @spots = Spot.all.page(params[:page]).per(6)
    @areas = Area.all
    @purposes = Purpose.all
  end

  def new
    @spot = Spot.new
    @areas = Area.all
    @purposes = Purpose.all
  end

  def create
    @areas = Area.all
    @purposes = Purpose.all
    @spot = Spot.new(spot_params)
    @spot.save
    redirect_to admin_spots_path
  end

  def edit
    @areas = Area.all
    @purposes = Purpose.all
    @spot = Spot.find(params[:id])
  end

  def update
    @areas = Area.all
    @purposes = Purpose.all
    @spot = Spot.find(params[:id])
    @spot.update(spot_params)
    redirect_to admin_spots_path
  end

  def destroy
    @spots = Spot.find(params[:id])
    @spots.destroy
    redirect_to admin_spots_path
  end

  private

  def spot_params
    params.require(:spot).permit(:area_id, :purpose_id, :name, :description, :image)
  end

end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :age])
  end
  
  # ログイン後の先
  def after_sign_in_path_for(resource)
   case resource
   when Admin
    admin_areas_path
   when User
    about_path
   end
  end
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  # ゲストログイン
  def new_guest
    user = User.find(1)
    user.update(email: 'guest@example.com',name: 'ゲストユーザー') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
    sign_in user
    redirect_to about_path
  end
  
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/areas_helper.rb
module Admin::AreasHelper
end

app/helpers/admin/purposes_helper.rb
module Admin::PurposesHelper
end

app/helpers/admin/spots_helper.rb
module Admin::SpotsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>©2021 京へようこそ</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg">
    <ul class="nav">
<% if user_signed_in? %>
      <li class="log">
        <a href="/">
          <%= image_tag 'logo.jpg', size: '80x80' %>
         </a>
      </li>
      <li class="nav-list"><%= link_to "マイページ",user_path(current_user) ,style:"color: #ee827c;" %></li>
      <li class="nav-list"><%= link_to "エリアで探す",areas_path ,style:"color: #ee827c;" %></li>
      <li class="nav-list"><%= link_to "目的で探す",purposes_path ,style:"color: #ee827c;" %></li>
      <li class="nav-list"><%= link_to "ログアウト",destroy_user_session_path , method: :delete ,style:"color: #ee827c;" %></li>
      <li id="searche"><%= render 'public/searches/searche', search: @search %></li>
<% elsif admin_signed_in? %>
      <li class="log">
        <a href="/">
          <%= image_tag 'logo.jpg', size: '80x80' %>
         </a>
      </li>
      <li class="nav-list"><%= link_to "エリア一覧",admin_areas_path %></li>
      <li class="nav-list"><%= link_to "目的一覧",admin_purposes_path %></li>
      <li class="nav-list"><%= link_to "スポット一覧",admin_spots_path %></li>
      <li class="nav-list"><%= link_to "ログアウト",destroy_admin_session_path , method: :delete %></li>
<% else %>
<% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>京へようこそ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="main">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>